### ISSUE TITLE
Build fails due to re-adding _DEBUG even in Release builds

### ISSUE THREAD

**Issue by adamrankin** [Slicer/opencv#1]
Workaround for using Release python with Debug OpenCV causes conflicts when using Release OpenCV

**Comment by jcfr** [comment]
Closing. This should have been addressed in branch [Slicer/opencv@slicer-4.1.2-2020.02.22-1a5bc6](https://github.com/Slicer/opencv/commits/slicer-4.1.2-2020.02.22-1a5bc6) by https://github.com/Slicer/opencv/commit/28aa55a75fe46bdda4a851b220485650f154d07f

Also here is a similar fix integrated in branch [Slicer/opencv@slicer-4.5.5-2021.12.25-dad26339a9](https://github.com/Slicer/opencv/tree/slicer-4.5.5-2021.12.25-dad26339a9), see https://github.com/Slicer/opencv/commit/7ab1af39429f208bf0a7affe9683bb509cdda5e9
